[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
curachain = "FRM52RYMbEqwb4WuBv6E7aiHv16acVZ1wBYaNRDYsnoh"

[programs.localnet]
curachain = "ACVeDFAirffL1Tx3QggFewJWajywkpXApJsknyrML57r"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./turbin3-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
